# Generated by Django 5.0.4 on 2024-06-24 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('dob', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('min_salary', models.CharField(max_length=50)),
                ('max_salary', models.CharField(max_length=50)),
                ('jobtype', models.CharField(max_length=50)),
                ('jobcategory', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('highestedu', models.CharField(max_length=50)),
                ('experiance', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('shift', models.CharField(max_length=50)),
                ('jobdesc', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='app/Img/Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('website', models.CharField(default='', max_length=150)),
                ('desc', models.CharField(default='', max_length=150)),
                ('logo_pic', models.ImageField(upload_to='app/Img/Compony')),
            ],
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('otp', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
                ('is_varified', models.BooleanField(default=False)),
                ('is_active', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=250)),
                ('componyname', models.CharField(max_length=250)),
                ('componyaddress', models.CharField(max_length=250)),
                ('qualification', models.CharField(max_length=250)),
                ('jobdesc', models.TextField(max_length=500)),
                ('componydesc', models.TextField(max_length=500)),
                ('responsibilties', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('componywebsite', models.CharField(max_length=250)),
                ('componyemail', models.CharField(max_length=250)),
                ('componycontact', models.CharField(max_length=250)),
                ('salarypackage', models.CharField(max_length=250)),
                ('experiace', models.IntegerField(default=0)),
                ('logo', models.ImageField(default='', upload_to='app/img/jobpost')),
                ('compony_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=200)),
                ('expiriance', models.CharField(default='', max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('min_salary', models.CharField(max_length=200)),
                ('max_salary', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('resume', models.FileField(upload_to='app/resume')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.postjobs')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermaster'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermaster'),
        ),
    ]
