# Generated by Django 4.1.7 on 2023-04-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_applylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='applylist',
            name='expiriance',
            field=models.CharField(default='', max_length=200),
        ),
    ]
