# Generated by Django 4.1.7 on 2023-05-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_applylist_expiriance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='is_active',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
