from django.db import models

# Create your models here.
class UserMaster(models.Model):
    email=models.EmailField(max_length=50)
    password=models.CharField(max_length=50)
    otp=models.IntegerField()
    role=models.CharField(max_length=50)
    is_varified= models.BooleanField(default=False)
    is_active=models.DateTimeField(auto_now_add=True)
    is_updated=models.DateTimeField(auto_now_add=True)

class Candidate(models.Model):
    user_id=models.ForeignKey(UserMaster,on_delete=models.CASCADE)
    firstname=models.CharField(max_length=50)
    lastname=models.CharField(max_length=50)
    contact=models.CharField(max_length=50)
    state=models.CharField(max_length=50)
    city=models.CharField(max_length=50)
    address=models.CharField(max_length=150)
    dob=models.CharField(max_length=50)
    gender=models.CharField(max_length=50)
    min_salary=models.CharField(max_length=50)
    max_salary=models.CharField(max_length=50)
    jobtype=models.CharField(max_length=50)
    jobcategory=models.CharField(max_length=50)
    country=models.CharField(max_length=50)
    highestedu=models.CharField(max_length=50)
    experiance=models.CharField(max_length=50)
    website=models.CharField(max_length=50)
    shift=models.CharField(max_length=50)
    jobdesc=models.CharField(max_length=50)
    profile_pic=models.ImageField(upload_to="app/Img/Candidate")

class Company(models.Model):
    user_id=models.ForeignKey(UserMaster,on_delete=models.CASCADE)
    firstname=models.CharField(max_length=50)
    lastname=models.CharField(max_length=50)
    company_name=models.CharField(max_length=150)
    state=models.CharField(max_length=50)
    city=models.CharField(max_length=50)
    contact=models.CharField(max_length=50)
    address=models.CharField(max_length=150)
    website=models.CharField(max_length=150,default="")
    desc=models.CharField(max_length=150,default="")
    logo_pic=models.ImageField(upload_to="app/Img/Compony")

class PostJobs(models.Model):
    compony_id=models.ForeignKey(Company,on_delete=models.CASCADE)
    jobname=models.CharField(max_length=250)
    componyname=models.CharField(max_length=250)
    componyaddress=models.CharField(max_length=250)
    qualification=models.CharField(max_length=250)
    jobdesc=models.TextField(max_length=500)
    componydesc=models.TextField(max_length=500)
    responsibilties=models.CharField(max_length=250)
    location=models.CharField(max_length=250)
    componywebsite=models.CharField(max_length=250)
    componyemail=models.CharField(max_length=250)
    componycontact=models.CharField(max_length=250)
    salarypackage=models.CharField(max_length=250)
    experiace=models.IntegerField(default=0)
    logo=models.ImageField(upload_to="app/img/jobpost",default="")
    
class ApplyList(models.Model):
    candidate=models.ForeignKey(Candidate,on_delete=models.CASCADE)
    job=models.ForeignKey(PostJobs,on_delete=models.CASCADE)
    education=models.CharField(max_length=200)
    expiriance=models.CharField(max_length=200,default="")
    website=models.CharField(max_length=200)
    min_salary=models.CharField(max_length=200)
    max_salary=models.CharField(max_length=200)
    gender=models.CharField(max_length=200)
    resume=models.FileField(upload_to='app/resume')